name: Build Kinoite
on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      image-registry: ghcr.io/ublue-os
      image-name: kinoite
      platforms: amd64, arm64
      tags: test
