name: Build Image

on:
  workflow_call:
    inputs:
      image-registry:
        description: "The registry to push the image to.  E.G. ghcr.io/ublue-os"
        required: true
        type: string
      image-name:
        description: "The name of the image to build.  E.G. main"
        required: true
        type: string
      platforms:
        description: "The platforms to build for.  E.G. aarch64, x86_64 etc"
        required: true
        type: string
      tags:
        description: "The tags to apply to the image"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.fedora_version }}-${{ inputs.fedora_edition }}-${{ inputs.platforms }}
  cancel-in-progress: true

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix
        id: set-matrix
        env:
          PLATFORMS: ${{ inputs.platforms }}
        run: |
          MATRIX='{"include":[]}'
          # Split platforms string by comma and iterate over each platform
          for platform in $(echo $PLATFORMS | tr ',' '\n'); do
            MATRIX=$(echo $MATRIX | jq ".include += [{\"platform\": \"${platform}\"}]")
          done

          echo "matrix=$(echo $MATRIX | jq -c  '.')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-22.04
    needs: generate_matrix
    strategy:
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Image
        id: build-image
        env:
          IMAGE_REGISTRY: ${{ inputs.image-registry }}
          IMAGE_NAME: ${{ inputs.image-name }}
          BUILD_ARGS_JSON: tojson(${{ inputs.build-args }})
        run: |
          podman build \
            --iidfile /tmp/iidfile \
            -t ${IMAGE_REGISTRY}/${IMAGE_NAME}:local \
            .

          IMAGE_ID=$(cat /tmp/iidfile)
          IMAGE_DIGEST=$(podman inspect --format '{{.Digest}}' $IMAGE_ID)

          echo "IMAGE_DIGEST=${IMAGE_DIGEST}" >> $GITHUB_OUTPUT

      - name: Push Image
        env:
          IMAGE_REGISTRY: ${{ inputs.image-registry }}
          IMAGE_NAME: ${{ inputs.image-name }}
          IMAGE_DIGEST: ${{ steps.build-image.outputs.IMAGE_DIGEST }}
        run: |
          for i in {1..3}; do
            echo "podman push --digestfile=/tmp/digestfile ${IMAGE_REGISTRY}/${IMAGE_NAME}@${IMAGE_DIGEST}" && break || sleep $((10 ** i))
            sleep 5
          done

  manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Manifest
        env:
          IMAGE_REGISTRY: ${{ inputs.image-registry }}
          IMAGE_NAME: ${{ inputs.image-name }}
        run: |
          podman manifest create ${IMAGE_REGISTRY}/${IMAGE_NAME}
